import type { AudienceId } from "./quick-add-options";

export const ITEM_SELECTIONS = [
  "Top",
  "Bottom",
  "Set",
  "One Piece",
  "Innerwear",
  "Footwear",
  "Accessories",
] as const;

export type ItemSelection = (typeof ITEM_SELECTIONS)[number];

const CATEGORY_MAP: Record<AudienceId, Partial<Record<ItemSelection, string[]>>> = {
  men: {
    Top: [
      "Plain Shirts",
      "Designer Shirts",
      "Linen Shirts",
      "Check Shirts",
      "Striped Shirts",
      "Printed Shirts",
      "Half Sleeve Shirts",
      "Full Sleeve Shirts",
      "Casual Shirts",
      "Formal Shirts",
      "Party Wear Shirts",
      "Denim Shirts",
      "Corduroy Shirts",
      "Flannel Shirts",
      "Oversized Shirts",
      "Shackets",
      "T-Shirts",
      "Plain T-Shirts",
      "Graphic T-Shirts",
      "Oversized T-Shirts",
      "Polo T-Shirts",
      "Henley T-Shirts",
      "Sleeveless T-Shirts",
      "Tank Tops",
      "Vests",
      "Hoodies",
      "Sweatshirts",
      "Sweaters",
      "Jackets",
      "Denim Jackets",
      "Leather Jackets",
      "Blazers",
      "Coats",
      "Winter Wear",
      "Kurtas",
      "Sherwanis",
      "Nehru Jackets",
      "Ethnic Wear",
      "Wedding Wear",
      "Gym Wear",
      "Sports T-Shirts",
      "Compression T-Shirts",
      "Innerwear",
    ],
    Bottom: [
      "Cargo Pants",
      "Jeans",
      "Chinos",
      "Linen Pants",
      "Corduroy Pants",
      "Shorts",
      "Joggers",
      "Trousers",
      "Formal Trousers",
      "Casual Pants",
      "Track Pants",
      "Sweatpants",
      "Cargo Shorts",
      "Denim Shorts",
      "Gym Shorts",
      "Lounge Pants",
      "Pyjamas",
      "Dhoti",
      "Ethnic Bottoms",
    ],
    Set: [
      "Shirt & Pant Set",
      "Shirt & Shorts Set",
      "T-Shirt & Jogger Set",
      "T-Shirt & Shorts Set",
      "Co-ord Set",
      "Tracksuit Set",
      "Kurta Set",
      "Sherwani Set",
      "Ethnic Set",
      "Wedding Set",
      "Party Wear Set",
      "Gym Set",
      "Night Suit",
      "Lounge Set",
      "Innerwear Set",
    ],
  },
  women: {
    Top: [
      "Tops",
      "Casual Tops",
      "Party Wear Tops",
      "Crop Tops",
      "Tank Tops",
      "Camisoles",
      "T-Shirts",
      "Oversized T-Shirts",
      "Graphic T-Shirts",
      "Polo T-Shirts",
      "Shirts",
      "Formal Shirts",
      "Casual Shirts",
      "Kurtis",
      "Tunics",
      "Blouses",
      "Shrugs",
      "Hoodies",
      "Sweatshirts",
      "Sweaters",
      "Jackets",
      "Blazers",
      "Ethnic Wear",
      "Wedding Wear",
      "Gym Wear",
      "Sports Bras",
      "Innerwear",
      "Bras",
    ],
    Bottom: [
      "Jeans",
      "Pants",
      "Trousers",
      "Leggings",
      "Jeggings",
      "Palazzos",
      "Skirts",
      "Shorts",
      "Joggers",
      "Track Pants",
      "Cargo Pants",
      "Wide Leg Pants",
      "Formal Pants",
      "Gym Leggings",
      "Lounge Pants",
      "Pyjamas",
      "Salwars",
      "Churidars",
      "Sharara",
      "Gharara",
      "Ethnic Bottoms",
    ],
    Set: [
      "Top & Bottom Set",
      "Co-ord Set",
      "Kurti Set",
      "Kurta Set",
      "Kurta Palazzo Set",
      "Salwar Suit Set",
      "Anarkali Set",
      "Lehenga Set",
      "Saree Set",
      "Ethnic Set",
      "Wedding Set",
      "Party Wear Set",
      "Gym Set",
      "Tracksuit Set",
      "Night Suit",
      "Lounge Set",
    ],
    "One Piece": [
      "Dresses",
      "Maxi Dresses",
      "Midi Dresses",
      "Mini Dresses",
      "Gowns",
      "Jumpsuits",
      "Rompers",
      "Sarees",
      "Lehengas",
    ],
  },
  kids: {
    Top: [
      "T-Shirts",
      "Graphic T-Shirts",
      "Polo T-Shirts",
      "Shirts",
      "Tops",
      "Hoodies",
      "Sweatshirts",
      "Sweaters",
      "Jackets",
      "Party Wear",
      "Ethnic Wear",
      "School Wear",
      "Winter Wear",
      "Innerwear",
      "Vests",
    ],
    Bottom: [
      "Jeans",
      "Pants",
      "Trousers",
      "Shorts",
      "Joggers",
      "Track Pants",
      "Leggings",
      "Skirts",
      "Pyjamas",
      "Lounge Pants",
      "Ethnic Bottoms",
      "School Bottoms",
    ],
    Set: [
      "T-Shirt & Shorts Set",
      "Shirt & Pant Set",
      "Top & Legging Set",
      "Co-ord Set",
      "Tracksuit Set",
      "Ethnic Set",
      "Party Wear Set",
      "School Uniform Set",
      "Night Suit",
      "Lounge Set",
      "Baby Romper Set",
      "Dungaree Set",
    ],
  },
};

export function getCategoriesFor(
  audience: AudienceId | "" | null | undefined,
  itemSelection: ItemSelection | "" | null | undefined
): string[] {
  if (!audience || !itemSelection) return [];
  return CATEGORY_MAP[audience]?.[itemSelection] ?? [];
}

/**
 * Flatten the category map into a single sorted, deduplicated list of every
 * category name across all departments. Used as the search-suggestion source
 * in the navbar search — gender / department is intentionally excluded so a
 * customer picks a category first and chooses department on the explore page.
 */
export function getAllCategories(): string[] {
  const set = new Set<string>();
  for (const byItem of Object.values(CATEGORY_MAP)) {
    for (const list of Object.values(byItem ?? {})) {
      for (const cat of list ?? []) set.add(cat);
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b));
}
